[manifest] # Header for the file, this should only be here once at the beginning
version = "0.1.0"
priority = 0 # Priority for loading the file

[[patches]]
[patches.pattern]
target = '=[SMODS _ "src/utils.lua"]' # The file you want to patch.
pattern = '''
if k == 'm_wild' or G.P_CENTERS[k].any_suit then return true end
''' # The line(s) you want to patch. In pattern patches it should be the whole line(s). Make sure it's unique in that file.
position = "at" # Where you want to patch it: 'before', 'after' or 'at' (this last one replaces the whole pattern)
payload = '''
if (k == 'm_wild' and not next(SMODS.find_card('j_sxf_mr_rorschach'))) or G.P_CENTERS[k].any_suit then return true end
''' # What code you want to replace it with.
match_indent = true